### PR TITLE
update dependencies to address vulnerability

### PR DESCRIPTION
**Pull request by pkrohn-sfdc**
## What does this PR do?

Updates `urllib3` to address a vulnerability; `s3transfer` is along for the ride.

## Why is this change being made?

[W-9075974: [sev:moderate] Vulnerability in krux/python-krux-boto-ec2](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000009Xb7YAE/view)

## How does this PR do it?

These are the changes made by `pipenv update`

## How was this tested? How can the reviewer verify your testing?

Relying on unit tests.

## Completion checklist

- [x] The pull request has been appropriately labeled according to
  our [conventions](https://kruxdigital.jira.com/wiki/display/EN/Changes+and+Peer+Review).
- [x] The version of the package has been updated according to [Semantic Versioning](http://semver.org/).
- [x] The change has unit & integration tests as appropriate.
- [x] Documentation is up to date and correct.
- [ ] Dependencies are correctly listed under `requirements.pip` and
      are up to date without going over a major version.
- [x] Stakeholders have been notified. Workflow-impacting changes have
      been appropriately socialized to avoid surprises.
- [x] The change is either small or have been canaried in the appropriate environment(s).

### CODE REVIEW

**Review by dcrampton-sfdc — APPROVED** [review]

**Comment by pkrohn-sfdc** [comment]
retest this please

**Comment by pkrohn-sfdc** [comment]
retest this please

**Comment by pkrohn-sfdc** [comment]
restest this please

**Comment by pkrohn-sfdc** [comment]
retest this please

**Comment by pkrohn-sfdc** [comment]
retest this please

**Comment by pkrohn-sfdc** [comment]
retest this please

**Comment by pkrohn-sfdc** [comment]
retest this please

**Pull request merged**
