### PR TITLE
Upgrading krux-stdlib

### PR DESCRIPTION
**Pull request by hanpeter**
This is to get the bug fix from `krux-stdlib`. Refer to [this PR](https://github.com/krux/python-krux-stdlib/pull/36) for the bug details.

### CODE REVIEW

**Comment by paul-krohn** [comment]
👍

**Comment by plathrop** [comment]
I recommend keeping your dependencies sorted alphabetically.

**Comment by plathrop** [comment]
+1, assuming this is the new, complete, list of all dependencies including transitive ones.

**Comment by hanpeter** [comment]
Instead of trying to fix `requirements.pip` to match the `pip==1.4.1`, I decided to upgrade pip on jenkins job.

**Pull request merged**
