### PR TITLE
Boto without hideous multi-inheritance nonsense

### PR DESCRIPTION
**Pull request by hitherto**

### CODE REVIEW

**Comment by hanpeter** [comment]
All sounds good except two things:
1. Let's modify the `cli.py` to use `get_boto()` function as well.
1. Let's move the comments into README.

**Comment by plathrop** [comment]
Actually the comments belong in the function's docstring. I don't object to putting them in README as well, but definitely in the docstring.

**Comment by hitherto** [comment]
LGTM

**Comment by hanpeter** [comment]
ok to test

**Pull request merged**
